---
title: "Projekt z analizy danych"
author: "Bartłomiej Smolski"
date: "`r Sys.Date()`"
output: 
  html_document: 
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache=TRUE)
```

# Wczytanie bibliotek
```{r biblioteki, result='hide'}
library(dplyr, warn.conflicts = FALSE)
library(tidyr, warn.conflicts = FALSE)
library(ggplot2, warn.conflicts = FALSE)
library(readxl, warn.conflicts = FALSE)
```

```{r funkcje, echo=FALSE, result='hide'}
f <- function(col1, col2) {
    if (is.na(col1)) {
      col2
    } else if (is.na(col2)) {
      col1
    } else {
      mean(c(col1, col2))
    }
}

f <-Vectorize(f)  

```

# Zapewnienie powtarzalności???
```{r powtarzalność, result='hide'}
set.seed(997)
```



# Wczytanie danych

```{r wczytanie, result='hide'}
bitcoin_diff <- read.csv("data/Bitcoin/BCHAIN-DIFF.csv", header=TRUE)
bitcoin_diff[,1] <- as.POSIXct(strptime(bitcoin_diff[,1], "%Y-%m-%d"))

bitcoin_hrate <- read.csv("data/Bitcoin/BCHAIN-HRATE.csv", header=TRUE)
bitcoin_hrate[,1] <- as.POSIXct(strptime(bitcoin_hrate[,1], "%Y-%m-%d"))

bitcoin_mkpru <- read.csv("data/Bitcoin/BCHAIN-MKPRU.csv", header=TRUE)
bitcoin_mkpru[,1] <- as.POSIXct(strptime(bitcoin_mkpru[,1], "%Y-%m-%d"))

bitcoin_trvou <- read.csv("data/Bitcoin/BCHAIN-TRVOU.csv", header=TRUE)
bitcoin_trvou[,1] <- as.POSIXct(strptime(bitcoin_trvou[,1], "%Y-%m-%d"))

currency_exchange_rates <- read.csv("data/CurrencyExchangeRates.csv", header=TRUE)
currency_exchange_rates[,1] <- as.POSIXct(strptime(currency_exchange_rates[,1], "%Y-%m-%d"))

gold_prices <- read.csv("data/Gold_prices.csv", header=TRUE, col.names = c("date", "USD_AM", "USD_PM", "GBP_AM",  "GBP_PM",  "EURO_AM", "EURO_PM"))
gold_prices[,1]  <- as.POSIXct(strptime(gold_prices[,1], "%Y-%m-%d"))

s_p_composite <- read.csv("data/S&PComposite.csv", header=TRUE)
s_p_composite[,1] <- as.POSIXct(strptime(s_p_composite[,1], "%Y-%m-%d"))

world_development_indicators <- read_excel("data/World_Development_Indicators.xlsx", sheet="Data")

```

```{r czyszczenie1, result='hide'}
#gold_prices <- mutate(gold_prices,USD=f(USD_AM,  USD_PM), GBP=f(GBP_AM, GBP_PM), EURO=f(EURO_AM, EURO_PM)) %>% 
#  select(date, USD, GBP, EURO) %>%
#  gather(currency, value, USD:EURO)

#s_p_composite <- gather(s_p_composite, measurment, value, S.P.Composite:Cyclically.Adjusted.PE.Ratio)

# world_development_indicators <- gather(world_development_indicators,year, value, "1970 [YR1970]":"2020 [YR2020]") %>% 
#mutate(year=as.POSIXct(strptime(sprintf('%s-12-31',substr(year, 1, 4)), "%Y-%m-%d")))
```

```{r czyszczenie2, result='hide'}
gold_prices <- mutate(gold_prices,USD=f(USD_AM,  USD_PM), GBP=f(GBP_AM, GBP_PM), EURO=f(EURO_AM, EURO_PM)) %>% 
  select(date, USD, GBP, EURO) 
s_p_composite <- gather(s_p_composite, measurment, value, S.P.Composite:Cyclically.Adjusted.PE.Ratio)

 world_development_indicators <- gather(world_development_indicators,year, value, "1970 [YR1970]":"2020 [YR2020]") %>% 
mutate(year=as.POSIXct(strptime(sprintf('%s-12-31',substr(year, 1, 4)), "%Y-%m-%d")))
```